<?
    $this->headTitle('Main','PREPEND');
    $this->headMeta()->appendName('keywords','ZF1')
            ->appendName('description', 'Main ZF1');
?>
<!--<pre>-->
<!--    id=--><?//=$this->lastid."\n"?>
<!--    --><?// print_r($this->posts);?>
<!--</pre>-->

<?// $url=$this->url(
//        [
//            'controller'=> 'index',
//            'action'=>'index',
//            'a'=> 333
//        ],
//        'default'
//    );?>
<!---->
<!--<a href="--><?//= $url?><!--"> Ref</a>-->

<!--<pre>-->
<!--    --><?// foreach ($this->posts as $post):?>
<!--        --><?// print_r($post)?>
<!--    --><?// endforeach; ?>
<!--</pre>-->
<?///*= $this->paginationControl($this->posts,'sliding','paginator.phtml')*/?>
<?//= $this->paginationControl($this->posts,'jumping','paginator.phtml')?>
<!---->
<!--<br/>-->
<?//= microtime(true)-$this->start; ?>

<?= $this->form?>




