<?php


namespace app\controllers;


use app\models\Category;
use Yii;
use app\models\TestForm;

class PostController extends AppController
{
    public $layout='basic';

//    public function beforeAction($action)
//    {
////        if($action->id==='index')
////        {
////            $this->enableCsrfValidation=false;
////        }
//        return parent::beforeAction($action); // TODO: Change the autogenerated stub
//    }

    public function actionShow()
    {
        $this->view->title='One article';
        $this->view->registerMetaTag(['name'=>'description','content'=>"Create page"]);
//        $this->layout='basic';

//        $cats= Category::find()->asArray()->where('parent=691')->orderBy(['id'=>SORT_DESC])->all();
//        $cats= Category::find()->asArray()->where( ['parent'=>691])->orderBy(['id'=>SORT_DESC])->all();
//        $cats= Category::find()->asArray()->where( ['like','title','pp'])->orderBy(['id'=>SORT_DESC])->all();
//        $cats= Category::find()->asArray()->where( ['<=','id','691'])->orderBy(['id'=>SORT_DESC])->all();
//        $cats= Category::find()->asArray()->where( ['<=','id','695'])->orderBy(['id'=>SORT_DESC])->limit(1)->all();
//        $cats= Category::find()->asArray()->where( ['<=','id','695'])->orderBy(['id'=>SORT_DESC])->one();
//        $cats= Category::find()->asArray()->where( ['<=','id','695'])->orderBy(['id'=>SORT_DESC])->count();
//        $cats= Category::findOne(['parent'=>691]);
//        $cats= Category::findAll(['parent'=>691]);

//        $query= <<<SQL
// select * from categories where parent=691
//SQL;
//        $cats= Category::findBySql($query)->asArray()->all();

//        $query= <<<SQL
// select * from categories where parent=:search
//SQL;
//        $cats= Category::findBySql($query,[':search'=>691])->asArray()->all();

//        $cats= Category::findOne('694');
//        $cats=$cats->products;

//        $cats= Category::find()->all();
//        foreach ($cats as $k=>$v)
//        {
//            $cats[$k]=$v->products;
//        }

//          $cats= Category::find()->with('products')->all();




        return $this->render('show',compact('cats'));
    }
    public function actionIndex()
    {
        if(Yii::$app->request->isAjax){
            ebug(Yii::$app->request->post());
            return;
        }

//        $post=TestForm::findOne(1);
//        $post->email='2@2.com';
//        $post->save();
//        $post->delete();
        TestForm::deleteAll(['>','id',3]);
        $model=new TestForm();
//        $model->name='Имя';
//        $model->email='mail@mail.com';
//        $model->text='Текст сообщения';
//        $model->save();
//        if($model->load(Yii::$app->request->post()))
//        {
////            ebug($model);
//            if($model->validate())
//            {
//                Yii::$app->session->setFlash('success','Success');
//                return $this->refresh();
//            }
//            else
//            {
//                Yii::$app->session->setFlash('error','Error');
//            }
//        }
        if($model->load(Yii::$app->request->post()))
        {
//            ebug($model);
            if($model->save())
            {
                Yii::$app->session->setFlash('success','Success');
                return $this->refresh();
            }
            else
            {
                Yii::$app->session->setFlash('error','Error');
            }
        }

        return $this->render('test',compact('model'));
    }
}